# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('site_description', models.CharField(default='Site Description', max_length=500)),
                ('site_url', models.CharField(default='example.com', max_length=300)),
                ('facebook', models.URLField(default='facebook.com', max_length=300)),
                ('twitter', models.URLField(default='twitter.com', max_length=300)),
                ('youtube', models.URLField(default='youtube.com', max_length=300)),
                ('linkedin', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('contact_title', models.CharField(default='Bu bölümden bana ulaşabilirsiniz.', max_length=1000)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
