# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='slug')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
