# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
